TheLittleOrangeChannel/TheLittleOrangeChannel/Controllers/ParcelasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Data;
using System.Data.Entity;
using System.Net;
using TheLittleOrangeChannel.Models;
using System.Net.Http;
using TheLittleOrangeChannel.Controllers.Shared;

namespace TheLittleOrangeChannel.Controllers
{
    public class ParcelasController : Controller
    {

        private TheLittleOrangeEntities db = new TheLittleOrangeEntities();

        // GET: Parcelas
        public ActionResult Index(string strCriterio)
        {

            DateTime _dtLimite = DateTime.Now.AddDays(10);

            var tblParcelas = db.tblParcelas.Include(t => t.tblPrestador).Include(t => t.tblAssinaturas).Include(t => t.tblStatus);
            if (!String.IsNullOrEmpty(strCriterio))
            {
                tblParcelas = tblParcelas.Where(h => h.Rastreador.Contains(strCriterio.ToString())
                                            || h.tblPrestador.Empresa.Contains(strCriterio.ToString())
                                            || h.tblStatus.Descricao.Contains(strCriterio.ToString())

                                            );
            }

            ViewBag.FiltroStatus = strCriterio;
            return View(tblParcelas.ToList());

        }

        public ActionResult ParcelasemAberto(string strCriterio)
        {
            // .......... mostra somente as parcelas em aberto para os proximos 10 dias
            // com isto evita de dar baixa em parcelas dos proximos meses

            DateTime _dtLimite = DateTime.Now.AddDays(10);
            tblStatus _tblStatus = db.tblStatus.Where(x => x.Objeto == "PARCELA" && x.Descricao == "ABERTA").FirstOrDefault();

            var tblParcelas = db.tblParcelas.Include(t => t.tblPrestador).Include(t => t.tblAssinaturas).Include(t => t.tblStatus);

            tblParcelas = tblParcelas.Where(h => h.idStatus == _tblStatus.idStatus && h.dataVencimento <= _dtLimite);                           

            if (!String.IsNullOrEmpty(strCriterio))
            {
                tblParcelas = tblParcelas.Where(h=>h.Rastreador.Contains(strCriterio.ToString())
                                              || h.tblPrestador.Empresa.Contains(strCriterio.ToString())
                                            );
            }

            ViewBag.FiltroStatus = strCriterio;
            return View(tblParcelas.ToList());

        }

        public ActionResult BaixaManual(int? id, decimal valor, int operador)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            tblParcelas tblParcela = db.tblParcelas.Find(id);
            if (tblParcela == null)
            {
                return HttpNotFound();
            }
            //.................... valida parcela

            baixaParcela(id, valor, operador);


            return RedirectToAction("Index", new { strCriterio = "ABERTA" });

        }

        private void baixaParcela(int? id, decimal valor, int operador)
        {
            tblUsuario _tblOperador = db.tblUsuario.Where(x => x.idUsuario == operador).FirstOrDefault();
            var _log = _tblOperador.Nome + " - " + DateTime.Now.AddDays(2).ToString();
            //....................... atualiza a Parcela
            tblStatus _tblStatus = db.tblStatus.Where(x => x.Objeto == "PARCELA" && x.Descricao == "PAGA").FirstOrDefault();
            tblParcelas _tblParcela = db.tblParcelas.Find(id);

            _tblParcela.dataPagamento = DateTime.Now;
            _tblParcela.idStatus = _tblStatus.idStatus;
            _tblParcela.valorPago = valor;
            _tblParcela.Log = _tblParcela.Log + "chr(13)" + _log;

            //....................... renova a Assinatura
            tblStatus _tblStatusAssinatura = db.tblStatus.Where(x => x.Objeto == "ASSINATURA" && x.Descricao == "ATIVA").FirstOrDefault();
            tblAssinaturas _tblAssinatura = db.tblAssinaturas.Where(x => x.idAssinatura == _tblParcela.idAssinatura).FirstOrDefault();

            // ............ calcula data de termino
            string plano = _tblAssinatura.Rastreador.Substring(4, 2);
            tblDominios _tblDuracao = db.tblDominios.Where(x => x.Objeto == "PRAZOPLANO" && x.Codigo == plano).FirstOrDefault();
            int qtdeMeses = Int32.Parse(_tblDuracao.Descricao);
            DateTime _novoVencto = (DateTime)_tblAssinatura.dtTermino;
            _novoVencto = _novoVencto.AddMonths(qtdeMeses);

            _tblAssinatura.idStatus = _tblStatusAssinatura.idStatus;
            _tblAssinatura.dtTermino = _novoVencto;
            _tblAssinatura.Log = _tblAssinatura.Log + "chr(13)" + _log + " novo vencto: " + _novoVencto.ToString();



            //....................... atualiza a Abrangencia no Prestador
            tblPrestador _tblPrestador = db.tblPrestador.Where(x =>x.idPrestador == _tblAssinatura.idPrestador).FirstOrDefault();
            tblStatus _tblStatusPrestador = db.tblStatus.Where(x => x.Objeto == "PRESTADOR" && x.Descricao == "ATIVO").FirstOrDefault();

            _tblPrestador.idAbrangencia = _tblAssinatura.idAbrangencia;
            _tblPrestador.idStatus = _tblStatusPrestador.idStatus;

            db.SaveChanges();

            //....................... cria nova parcela
            PrestadoresController _prestadores = new PrestadoresController();
            _prestadores.CriarParcela(_tblAssinatura.idAssinatura);

            //........................ TODO lancamento contas a RECEBER

            //........................ TODO lancamento conta Comissao


        }




    }
}

TheLittleOrangeChannel/TheLittleOrangeChannel/Controllers/PrestadoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheLittleOrangeChannel.Models;
using System.Net.Http;

namespace TheLittleOrangeChannel.Controllers
{
    public class PrestadoresController : Controller
    {
        private TheLittleOrangeEntities db = new TheLittleOrangeEntities();


        // GET: Prestadores
        public ActionResult Menu()
        {
            return View();
        }

            // GET: Prestadores
        public ActionResult Index()
        {

            var tblStatusGroup = new StatusGroup();

            var tblPrestador = db.tblPrestador.Include(t => t.tblCondominio).Include(t => t.tblStatus);


            var tblPrestadorGroup = tblPrestador.GroupBy(x => x.tblStatus.Descricao).ToList();
            foreach (var group in tblPrestadorGroup)
            { 
            
            
            }
           
            return View(tblPrestador.ToList());
        }




        public class StatusGroup
        {
        
            public string Descricao { get; set; }
            public int qtde { get; set; }

        }





        // GET: Prestadores
        public ActionResult Prestadores(string strCriterio)
        {
            var tblPrestador = db.tblPrestador.Include(t => t.tblCondominio).Include(t => t.tblDominios).Include(t => t.tblUsuario).Include(t => t.tblStatus);
            if (!String.IsNullOrEmpty(strCriterio))
            {
                tblPrestador = tblPrestador.Where(h => h.Cidade.Contains(strCriterio.ToString())
                                            || h.Empresa.Contains(strCriterio.ToString())
                                            || h.UF.Contains(strCriterio.ToString())
                                            || h.tblCondominio.Nome.Contains(strCriterio.ToString())
                                            || h.tblStatus.Descricao.Contains(strCriterio.ToString())
                                            );
            }

            ViewBag.FiltroStatus = strCriterio;
            return View(tblPrestador.ToList());

        }





        // GET: Prestadores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPrestador tblPrestador = db.tblPrestador.Find(id);
            if (tblPrestador == null)
            {
                return HttpNotFound();
            }
            //.................. novos viewsbags

            var _tblCondominio = db.tblCondominio.Where(x => x.idCondominio == tblPrestador.idCondominio).FirstOrDefault();
            ViewBag.Condominio = _tblCondominio.Nome;

            var _tblIndicacao = db.tblUsuario.Where(x => x.idUsuario == tblPrestador.idCanal).FirstOrDefault();
            ViewBag.IndicadoPor = _tblIndicacao.Nome;


            //.....................................

            ViewBag.idCondominio = new SelectList(db.tblCondominio, "idCondominio", "Nome", tblPrestador.idCondominio);
            ViewBag.idAbrangencia = new SelectList(db.tblDominios, "idDominio", "Objeto", tblPrestador.idAbrangencia);
            ViewBag.idCanal = new SelectList(db.tblUsuario, "idUsuario", "Nome", tblPrestador.idCanal);
            ViewBag.idStatus = new SelectList(db.tblStatus, "idStatus", "Objeto", tblPrestador.idStatus);
            return View(tblPrestador);
        }





        // GET: Prestadores/Edit/5
        public ActionResult Empresa(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPrestador tblPrestador = db.tblPrestador.Find(id);
            if (tblPrestador == null)
            {
                return HttpNotFound();
            }

            //.................. novos viewsbags

            var _tblCondominio = db.tblCondominio.Where(x => x.idCondominio == tblPrestador.idCondominio).FirstOrDefault();
            ViewBag.Condominio = _tblCondominio.Nome;

            var _tblIndicacao = db.tblUsuario.Where(x => x.idUsuario == tblPrestador.idCanal).FirstOrDefault();
            ViewBag.IndicadoPor = _tblIndicacao.Nome;


            //.....................................

            ViewBag.idCondominio = new SelectList(db.tblCondominio, "idCondominio", "Nome", tblPrestador.idCondominio);
            ViewBag.idAbrangencia = new SelectList(db.tblDominios, "idDominio", "Objeto", tblPrestador.idAbrangencia);
            ViewBag.idCanal = new SelectList(db.tblUsuario, "idUsuario", "Nome", tblPrestador.idCanal);
            ViewBag.idStatus = new SelectList(db.tblStatus, "idStatus", "Objeto", tblPrestador.idStatus);
            return View(tblPrestador);
        }


        // GET: Prestadores/Abrangencia/5
        public ActionResult Abrangencia(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPrestador tblPrestador = db.tblPrestador.Find(id);
            if (tblPrestador == null)
            {
                return HttpNotFound();
            }
            //.................. novos viewsbags

            var _tblCondominio = db.tblCondominio.Where(x => x.idCondominio == tblPrestador.idCondominio).FirstOrDefault();
            ViewBag.Condominio = _tblCondominio.Nome;
            ViewBag.Cidade = _tblCondominio.Cidade;
            ViewBag.Estado = _tblCondominio.UF;

            var _tblIndicacao = db.tblUsuario.Where(x => x.idUsuario == tblPrestador.idCanal).FirstOrDefault();
            ViewBag.IndicadoPor = _tblIndicacao.Nome;

            var _tblAbrangencia = db.tblDominios.Where(x => x.idDominio == tblPrestador.idAbrangencia).FirstOrDefault();
            ViewBag.Abrangencia = _tblAbrangencia.Descricao;
            ViewBag.id = id;         
            
            return View(tblPrestador);
        }




        // GET: Prestadores/Planos/5
        public ActionResult Planos(int? id, string tipoAbrangencia)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPrestador tblPrestador = db.tblPrestador.Find(id);
            if (tblPrestador == null)
            {
                return HttpNotFound();
            }
            //.................. novos viewsbags
            
            var _tblCondominio = db.tblCondominio.Where(x => x.idCondominio == tblPrestador.idCondominio).FirstOrDefault();
            ViewBag.Condominio = _tblCondominio.Nome;
            ViewBag.Cidade = _tblCondominio.Cidade;
            ViewBag.Estado = _tblCondominio.UF;

            var _tblIndicacao = db.tblUsuario.Where(x => x.idUsuario == tblPrestador.idCanal).FirstOrDefault();
            ViewBag.IndicadoPor = _tblIndicacao.Nome;

            // ............... codigo dos planos
            var _tblPlanoMensal = db.tblDominios.Where(x => x.Objeto == "PLANO" && x.Descricao == "MENSAL").FirstOrDefault();
            var _tblPlanoAnual = db.tblDominios.Where(x => x.Objeto == "PLANO" && x.Descricao == "1 ANO").FirstOrDefault();
            var _tblPlano3Anos = db.tblDominios.Where(x => x.Objeto == "PLANO" && x.Descricao == "3 ANOS").FirstOrDefault();

            var codPlanoMensal = _tblPlanoMensal.Codigo;
            var codPlanoAnual = _tblPlanoAnual.Codigo;
            var codPlano3Anos = _tblPlano3Anos.Codigo;

            var _tblAbrangencia = db.tblDominios.Where(x => x.Objeto == "ABRANGENCIA" && x.Descricao == tipoAbrangencia).FirstOrDefault();
            var _tblValorPlano  = db.tblDominios.Where(x => x.Objeto == "VALORPLANO"  && x.Codigo == _tblAbrangencia.Codigo).FirstOrDefault();
            var _tblDescontoAno = db.tblDominios.Where(x => x.Objeto == "DESCONTO" && x.Codigo == codPlanoAnual).FirstOrDefault();
            var _tblDesconto3Ano = db.tblDominios.Where(x => x.Objeto == "DESCONTO" && x.Codigo == codPlano3Anos).FirstOrDefault();
            
            double _vlrPlanoMensal = Convert.ToDouble(_tblValorPlano.Descricao);
            double _percDescontoAno = Convert.ToDouble(_tblDescontoAno.Descricao);
            double _percDesconto3Anos = Convert.ToDouble(_tblDesconto3Ano.Descricao);
            double _vlrPlanoAnual = ((_vlrPlanoMensal * 12) - ((_vlrPlanoMensal * 12) * (_percDescontoAno / 100)));
            double _vlrPlano3Anos = ((_vlrPlanoMensal * 36) - ((_vlrPlanoMensal * 36) * (_percDesconto3Anos / 100)));

            ViewBag.codPlanoMensal = codPlanoMensal;
            ViewBag.codPlanoAnual = codPlanoAnual;
            ViewBag.codPlano3Anos = codPlano3Anos;

            ViewBag.Abrangencia = _tblAbrangencia.Descricao;              
            ViewBag.ValorPlanoMensal = String.Format("{0:C2}", _vlrPlanoMensal);
            ViewBag.ValorPlanoAnual = String.Format("{0:C2}",_vlrPlanoAnual);
            ViewBag.ValorPlano3Anos = String.Format("{0:C2}", _vlrPlano3Anos) ;

            ViewBag.vlPlanoMensal = _vlrPlanoMensal;
            ViewBag.vlPlanoAnual =  _vlrPlanoAnual;
            ViewBag.vlPlano3Anos =  _vlrPlano3Anos;

            ViewBag.id = id;
            var celular = tblPrestador.Celular;
            celular = celular.Replace(" ","");
            celular = celular.Replace("(", "");
            celular = celular.Replace(")", "");
            celular = celular.Replace("-", "");
            ViewBag.Celular = celular;
            ViewBag.Empresa = tblPrestador.Empresa;

            return View(tblPrestador);
        }


        // GET: Prestadores/FormaPagto/5
        public ActionResult FormaPagto(int? id, string tipoAbrangencia, string tipoPlano)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPrestador tblPrestador = db.tblPrestador.Find(id);

TheLittleOrangeChannel/TheLittleOrangeChannel/Views/Prestadores/Abrangencia - Cópia .cshtml
@using TheLittleOrangeChannel.Controllers.Shared;
@model TheLittleOrangeChannel.Models.tblPrestador
@{
    ViewBag.Title = "Abrangência";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="bg-fundo">
    @if (SessionProfile.Logado && (SessionProfile.ADM || SessionProfile.Canal))
    {
        <div class="form-horizontal">
            <div class="row">
                <div class="col-md-8">
                    <h3> @Html.DisplayFor(model => model.Empresa) </h3>
                </div>

                <div class="col-md-2">
                    <a href="@Url.Action("Menu", "Prestadores")"> <input type="button" value="Voltar" class="btn btn-default" /></a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <h5> Fone: @Html.DisplayFor(model => model.Celular) </h5>
                </div>
                <div class="col-md-10">
                    <h5>indicado por - @ViewBag.IndicadoPor do @ViewBag.Condominio de @ViewBag.Cidade - @ViewBag.Estado</h5>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <h5>Escolha até onde você quer ser encontrado</h5>
                </div>
                <div class="col-md-10">
                </div>
            </div>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.idPrestador)
            @Html.HiddenFor(model => model.idAbrangencia)
            @Html.HiddenFor(model => model.idPlano)
            @Html.HiddenFor(model => model.idFormaPagto)


            <div class="row">
                <div class="col-md-2">
                    &nbsp;
                </div>
                <div class="col-md-8">

                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Condominio" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Condominio</h4>
                        Free<br />Somente os moradores do @ViewBag.Condominio poderão te localizar!
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Cidade" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Cidade</h4>
                        R$26,00<br />
                        Todas os usuários da cidade de  @ViewBag.Cidade conseguirão te encontrar!
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Estado" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Estado</h4>
                        R$35,00<br />
                        Todas os usuários do estado de  @ViewBag.Estado conseguirão te encontrar!
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Regiao" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Região</h4>
                        R$53,00<br />
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Pais" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>País</h4>
                        R$143,00<br />
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Continente" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Continente</h4>
                        R$260,00<br />
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Mundial" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Mundial</h4>
                        R$350,00<br />
                    </a>

                </div>
                <div class="col-md-2">
                    &nbsp;
                </div>
            </div>

        </div>
    }
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script type="text/javascript">

    $(document).ready(function () {

        @*var escolha = "@ViewBag.Abrangencia";
        if (escolha != "") {
            Escolha("Abrangencia", escolha);
        }*@

    });

        function Escolha(Abrangencia)
        {

            //var cubagem = $("#Cubagem").val();
            var ln_prestador = document.getElementById("idPrestador").Value;
            var ls_Abrangecia = Abrangencia;
            alert(ln_prestador);
            alert(ls_Abrangecia);

        }






    </script>




}

TheLittleOrangeChannel/TheLittleOrangeChannel/Views/Prestadores/Abrangencia.cshtml
@using TheLittleOrangeChannel.Controllers.Shared;
@model TheLittleOrangeChannel.Models.tblPrestador
@{
    ViewBag.Title = "Abrangência";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="bg-fundo">
    @if (SessionProfile.Logado && (SessionProfile.ADM || SessionProfile.Canal))
    {
        <div class="form-horizontal">
            <div class="row">
                <div class="col-md-8">
                    <h3> @Html.DisplayFor(model => model.Empresa) </h3>
                </div>

                <div class="col-md-2">
                    <a href="@Url.Action("Menu", "Prestadores")"> <input type="button" value="Voltar" class="btn btn-default" /></a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <h5> Fone: @Html.DisplayFor(model => model.Celular) </h5>
                </div>
                <div class="col-md-10">
                    <h5>indicado por - @ViewBag.IndicadoPor do @ViewBag.Condominio de @ViewBag.Cidade - @ViewBag.Estado</h5>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <h5>Escolha até onde você quer ser encontrado</h5>
                </div>
                <div class="col-md-10">
                </div>
            </div>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.idPrestador)
            @Html.HiddenFor(model => model.idAbrangencia)
            @Html.HiddenFor(model => model.idPlano)
            @Html.HiddenFor(model => model.idFormaPagto)


            <div class="row">
                <div class="col-md-2">
                    &nbsp;
                </div>
                <div class="col-md-8">

                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Condominio" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Condominio</h4>
                        Free<br />Somente os moradores do @ViewBag.Condominio poderão te localizar!
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Cidade" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Cidade</h4>
                        R$26,00<br />
                        Todas os usuários da cidade de  @ViewBag.Cidade conseguirão te encontrar!
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Estado" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Estado</h4>
                        R$35,00<br />
                        Todas os usuários do estado de  @ViewBag.Estado conseguirão te encontrar!
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Regiao" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Região</h4>
                        R$53,00<br />
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Pais" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>País</h4>
                        R$143,00<br />
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Continente" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Continente</h4>
                        R$260,00<br />
                    </a>
                    <a href='@Url.Action("Planos", new { id = ViewBag.id, tipoAbrangencia = "Mundial" })' class="list-group-item list-group-item-action list-group-item-orange">
                        <h4>Mundial</h4>
                        R$350,00<br />
                    </a>

                </div>
                <div class="col-md-2">
                    &nbsp;
                </div>
            </div>

        </div>
    }
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script type="text/javascript">

    $(document).ready(function () {

        @*var escolha = "@ViewBag.Abrangencia";
        if (escolha != "") {
            Escolha("Abrangencia", escolha);
        }*@

    });

        function Escolha(Abrangencia)
        {

            //var cubagem = $("#Cubagem").val();
            var ln_prestador = document.getElementById("idPrestador").Value;
            var ls_Abrangecia = Abrangencia;
            alert(ln_prestador);
            alert(ls_Abrangecia);

        }






    </script>




}

TheLittleOrangeChannel/TheLittleOrangeChannel/Views/Prestadores/EnviaMsgTrafego.cshtml
@{
    ViewBag.Title = "Envio PagSeguro";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="bg-fundo">
        



            <div class="row">
                <div class="col-md-2">
                    &nbsp;
                </div>
                <div class="col-md-8">
                    <a href='@Url.Action("Menu")' class="list-group-item list-group-item-action list-group-item-orange">
                        <h1>@ViewBag.msg</h1>
                    </a>
                    <br />
                </div>
                <div class="col-md-2">
                    &nbsp;
                </div>
            </div>

        </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script type="text/javascript">

    $(document).ready(function () {

        @*var escolha = "@ViewBag.Abrangencia";
        if (escolha != "") {
            Escolha("Abrangencia", escolha);
        }*@

    });

        function Escolha(Abrangencia)
        {

            //var cubagem = $("#Cubagem").val();
            var ln_prestador = document.getElementById("idPrestador").Value;
            var ls_Abrangecia = Abrangencia;
            alert(ln_prestador);
            alert(ls_Abrangecia);

        }
    


      


    </script>




}

TheLittleOrangeChannel/TheLittleOrangeChannel/Views/Prestadores/EnvioPagSeguro.cshtml
@model TheLittleOrangeChannel.Models.tblPrestador

@{
    ViewBag.Title = "Envio PagSeguro";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="bg-fundo">
        <div class="form-horizontal">
            <div class="row">
                <div class="col-md-8">
                    <h3> @Html.DisplayFor(model => model.Empresa) </h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <h5> Fone: @Html.DisplayFor(model => model.Celular) </h5>
                </div>
            </div>
           
            <hr />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.idPrestador)
            @Html.HiddenFor(model => model.idAbrangencia)
            @Html.HiddenFor(model => model.idPlano)
            @Html.HiddenFor(model => model.idFormaPagto)


            <div class="row">
                <div class="col-md-2">
                    &nbsp;
                </div>
                <div class="col-md-8">
                    <a href='@Url.Action("Menu")' class="list-group-item list-group-item-action list-group-item-orange">
                        <h1>@ViewBag.msg</h1>
                    </a>
                    <br />
                </div>
                <div class="col-md-2">
                    &nbsp;
                </div>
            </div>

        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script type="text/javascript">

    $(document).ready(function () {

        @*var escolha = "@ViewBag.Abrangencia";
        if (escolha != "") {
            Escolha("Abrangencia", escolha);
        }*@

    });

        function Escolha(Abrangencia)
        {

            //var cubagem = $("#Cubagem").val();
            var ln_prestador = document.getElementById("idPrestador").Value;
            var ls_Abrangecia = Abrangencia;
            alert(ln_prestador);
            alert(ls_Abrangecia);

        }
    


      


    </script>




}