TheLittleOrangeChannel/TheLittleOrangeChannel/Controllers/PrestadoresBaseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheLittleOrangeChannel.Models;
using TheLittleOrangeChannel.Controllers.Shared;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using System.Text;
using System.Threading.Tasks;

//using EntityState = System.Data.EntityState;
//using System.Data.EntityState
//using Microsoft.EntityFrameworkCore

namespace TheLittleOrangeChannel.Controllers
{
    public class PrestadoresBaseController : Controller
    {
        private TheLittleOrangeEntities db = new TheLittleOrangeEntities();

        // GET: PrestadoresBase
        public ActionResult Index(string strCriterio, string strStatus)
        {
            var tblPrestadorBase = db.tblPrestadorBase.Include(t => t.tblCondominio).Include(t => t.tblEspecialidade).Include(t => t.tblUsuario).Include(t => t.tblStatus);
            if (!String.IsNullOrEmpty(strCriterio))
            {
                tblPrestadorBase = tblPrestadorBase.Where(h => h.Empresa.Contains(strCriterio.ToString())
                                            || h.Celular.Contains(strCriterio.ToString())
                                            || h.tblStatus.Descricao.Contains(strCriterio.ToString())
                                            || h.tblEspecialidade.Descricao.Contains(strCriterio.ToString())

                                            );
            }

            if (strStatus == null || strStatus == "") 
            {
                strStatus = "Cadastrado";
            }
            ViewBag.TipoPesquisado = strStatus;
            var _Status = db.tblStatus.Where(x => x.Objeto == "PRESTADORBASE" && x.Descricao == strStatus).FirstOrDefault();
            tblPrestadorBase = tblPrestadorBase.Where(h => h.idCanal == SessionProfile.idUsuario
                                                     && h.idStatus == _Status.idStatus
            );

            return View(tblPrestadorBase.ToList());

        }





        // GET: PrestadoresBase/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPrestadorBase tblPrestadorBase = db.tblPrestadorBase.Find(id);
            if (tblPrestadorBase == null)
            {
                return HttpNotFound();
            }
            return View(tblPrestadorBase);
        }

        // GET: PrestadoresBase/Create
        public ActionResult Create()
        {

            var _StatusCondominio = db.tblStatus.Where(x => x.Objeto == "CONDOMINIO" && x.Descricao == "ATIVO").FirstOrDefault();
            var _StatusEspecialidade = db.tblStatus.Where(x => x.Objeto == "ESPECIALIDADE" && x.Descricao == "ATIVO").FirstOrDefault();

            var _StatusPrestador= db.tblStatus.Where(x => x.Objeto == "PRESTADORBASE" && x.Descricao == "Cadastrado").FirstOrDefault();
            var _Condominios = db.tblCondominio.Where(x => x.idStatus == _StatusCondominio.idStatus);
            var _Especialidade = db.tblEspecialidade.Where(x => x.idStatus == _StatusEspecialidade.idStatus).OrderBy(x=>x.Descricao);

            ViewBag.idEspecialidade = new SelectList(_Especialidade, "idEspecialidade", "Descricao");
            ViewBag.idCondominio = new SelectList(_Condominios, "idCondominio", "Nome");
            ViewBag.idCanal = new SelectList(db.tblUsuario, "idUsuario", "Nome", SessionProfile.idUsuario); 

            //ViewBag.idCanal = new SelectList(db.tblUsuario, "idUsuario", "Nome");
            ViewBag.idStatus = new SelectList(db.tblStatus, "idStatus", "Objeto");
            ViewBag.idPlano = new SelectList(db.tblDominios, "idDominio", "Objeto");
            ViewBag.idFormaPagto = new SelectList(db.tblDominios, "idDominio", "Objeto");
            ViewBag.idAbrangencia= new SelectList(db.tblDominios, "idDominio", "Descricao");


            //ViewBag.idAbrangencia = new SelectList(db.tblDominios, "idDominio", "Objeto", tblPrestador.idAbrangencia);
            //ViewBag.idCanal = new SelectList(db.tblUsuario, "idUsuario", "Nome", tblPrestador.idCanal);
            //ViewBag.idStatus = new SelectList(db.tblStatus, "idStatus", "Objeto", _StatusPrestador.idStatus);
            //ViewBag.idStatus =  _StatusPrestador.idStatus;


            return View();
        }

       



        // POST: PrestadoresBase/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idPrestador,idCondominio,idCanal,Empresa,Email,Celular,CPF_CNPJ,idEspecialidade,idStatus,dtCriacao,idPlano,idAbrangencia,diasPromocao,idFormaPagto")] tblPrestadorBase tblPrestadorBase)
        {
            tblPrestadorBase.diasPromocao = 0;
            tblPrestadorBase.dtCriacao = DateTime.Now;

            var celular = tblPrestadorBase.Celular;
            celular = celular.Replace(" ", "");
            celular = celular.Replace("(", "");
            celular = celular.Replace(")", "");
            celular = celular.Replace("-", "");
            celular = celular.Replace("/", "");
            tblPrestadorBase.Celular = celular;

            var _StatusCadastrado = db.tblStatus.Where(x => x.Objeto == "PRESTADORBASE" && x.Descricao == "Cadastrado").FirstOrDefault();
            var _Plano = db.tblDominios.Where(x => x.Objeto == "PLANO" && x.Descricao == "NOVO").FirstOrDefault();
            var _FormaPagto = db.tblDominios.Where(x => x.Objeto == "FORMAPAGTO" && x.Descricao == "NOVO").FirstOrDefault();
            var _Abrangencia = db.tblDominios.Where(x => x.Objeto == "ABRANGENCIA" && x.Descricao == "CONDOMINIO").FirstOrDefault();

            tblPrestadorBase.idCanal = SessionProfile.idUsuario;
            tblPrestadorBase.idStatus = _StatusCadastrado.idStatus;
            tblPrestadorBase.idPlano = _Plano.idDominio;
            tblPrestadorBase.idAbrangencia = _Abrangencia.idDominio;
            tblPrestadorBase.idFormaPagto = _FormaPagto.idDominio;

            if (ModelState.IsValid)
            {
                db.tblPrestadorBase.Add(tblPrestadorBase);
                db.SaveChanges();
                int _prestador = tblPrestadorBase.idPrestador;

                return RedirectToAction("Edit", new { id = _prestador });
            }

            return RedirectToAction("Index");
            //var _Abrangencia = db.tblDominios.Where(x => x.Objeto == "ABRANGENCIA");

            //ViewBag.idAbrangencia = new SelectList(_Abrangencia, "idDominio", "Descricao");
            //ViewBag.idEspecialidade = new SelectList(db.tblEspecialidade, "idEspecialidade", "Descricao");
            //ViewBag.idCondominio = new SelectList(db.tblCondominio, "idCondominio", "Nome", tblPrestadorBase.idCondominio);
            //ViewBag.idCanal = new SelectList(db.tblUsuario, "idUsuario", "Nome", tblPrestadorBase.idCanal);
            //ViewBag.idStatus = new SelectList(db.tblStatus, "idStatus", "Objeto", tblPrestadorBase.idStatus);
            //return View(tblPrestadorBase);
        }


        // POST: tblPrestadorBases/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult xCreate([Bind(Include = "idPrestador,idCondominio,idCanal,Empresa,Email,Celular,CPF_CNPJ,idEspecialidade,idStatus,dtCriacao,idPlano,idAbrangencia,diasPromocao,idFormaPagto")] tblPrestadorBase tblPrestadorBase)
        {
            if (ModelState.IsValid)
            {
                db.tblPrestadorBase.Add(tblPrestadorBase);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idCondominio = new SelectList(db.tblCondominio, "idCondominio", "Nome", tblPrestadorBase.idCondominio);
            ViewBag.idAbrangencia = new SelectList(db.tblDominios, "idDominio", "Objeto", tblPrestadorBase.idAbrangencia);
            ViewBag.idFormaPagto = new SelectList(db.tblDominios, "idDominio", "Objeto", tblPrestadorBase.idFormaPagto);
            ViewBag.idPlano = new SelectList(db.tblDominios, "idDominio", "Objeto", tblPrestadorBase.idPlano);
            ViewBag.idEspecialidade = new SelectList(db.tblEspecialidade, "idEspecialidade", "Area", tblPrestadorBase.idEspecialidade);
            ViewBag.idCanal = new SelectList(db.tblUsuario, "idUsuario", "Nome", tblPrestadorBase.idCanal);
            ViewBag.idStatus = new SelectList(db.tblStatus, "idStatus", "Objeto", tblPrestadorBase.idStatus);
            return View(tblPrestadorBase);
        }


        // GET: PrestadoresBase/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPrestadorBase tblPrestadorBase = db.tblPrestadorBase.Find(id);
            if (tblPrestadorBase == null)
            {
                return HttpNotFound();
            }

            var _StatusCadastrado = db.tblStatus.Where(x => x.Objeto == "PRESTADORBASE" && x.Descricao == "Cadastrado").FirstOrDefault();
            var _StatusIndicado = db.tblStatus.Where(x => x.Objeto == "PRESTADORBASE" && x.Descricao == "Indicado").FirstOrDefault();
            
            var _tblespecialidade = db.tblEspecialidade.Where(x => x.idEspecialidade == tblPrestadorBase.idEspecialidade).FirstOrDefault();
            var _tblCondominio = db.tblCondominio.Where(x => x.idCondominio == tblPrestadorBase.idCondominio).FirstOrDefault();

TheLittleOrangeChannel/TheLittleOrangeChannel/Views/PrestadoresBase/Condominio.cshtml
@using TheLittleOrangeChannel.Controllers.Shared;

@model IEnumerable<TheLittleOrangeChannel.Models.tblPrestadorBase>
@{
    ViewBag.Title = ViewBag.FiltroStatus;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="bg-fundo">
        @if (SessionProfile.Logado && (SessionProfile.ADM || SessionProfile.Canal))
        {
            <div class="row">
                <div class="col-md-12">
                    <h2>@ViewBag.Title</h2>
                    @using (Html.BeginForm())
                    {
                <p>
                    Procurar por : @Html.TextBox("strCriterio") &nbsp;
                    <input type="submit" value="Procurar" class="btn btn-warning" /> &nbsp;
                    <a href="@Url.Action("Create", "PrestadoresBase")"> <input type="button" value="Novo"   class="btn btn-default" /></a>
                </p>
                    }
                </div>
            </div>



            <div class="row">
                <div class="col-md-2">
                    &nbsp;
                </div>
                <div class="col-md-8">

                    @foreach (var item in Model)
                    {

                    <div class="list-group-item list-group-item-action list-group-item-orange" onclick="Edit('@item.idPrestador');" style="cursor: pointer">

                        <h4> @Html.DisplayFor(modelItem => item.tblCondominio.Nome) </h4>
                        <h3> @Html.DisplayFor(modelItem => item.Empresa) -  @Html.DisplayFor(modelItem => item.Celular)</h3>

                    </div>
                    }
                </div>
                <div class="col-md-2">
                    &nbsp;
                </div>
            </div>
        }
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script type="text/javascript">

            $(document).ready(function () {

               //' document.getElementById("btnProspectado").style.display = 'none';

               // var criterio = $("#strCriterio").val();
               // alert(criterio);

                @*var escolha = "@ViewBag.Abrangencia";
                if (escolha != "") {
                document.getElementById("divPropostas").style.display = 'none';
                    Escolha("Abrangencia", escolha);
                }*@

            });

           


            function Edit(idPrestador)
            {

                var url = '@Url.Action("Edit", "PrestadoresBase")?id=' + idPrestador;
                window.open(url,"_self");

            };



            function enviarTrafego(celular, empresa, condominio, idPrestador) {

                var celular = "55" + celular;

                var texto = empresa + " sua empresa foi indicada  para fazer parte do " +
                    "The Little Orange Club, porque você prestou serviços no " + condominio + ". \n \n" +
                    "Nosso aplicativo é uma plataforma para os moradores localizarem os prestadores de serviço. \n \n" +
                    "Para que sua empresa possa ser visualizada gratuitamente por todos os moradores do " + condominio + ", confirme seu cadastro em: \n \n" +
                    "TheLittleOrange.app \n\n";

                texto = window.encodeURIComponent(texto);
                window.open("https://api.whatsapp.com/send?phone=" + celular + "&text=" + texto, "_blank");

                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("AtualizaStatus", "Prestadores")',
                    data: {
                        "idPrestador": idPrestador,
                        "Status": 'Prospectado'
                    },
                    success:
                    function (resultado) {
                        alert(resultado);
                    },
                });
                location.reload();

           };




            function enviarProspectado(celular, empresa, condominio, idPrestador, cidade) {

                var celular = "55" + celular;

                var texto = "Pronto, sua empresa  já faz parte do The Little Orange Club. \n \n" +
                    "Este plano é gratuito e a " + empresa + " poderá ser vista somente pelos moradores do " + condominio + "! \n \n" +
                    "Temos outros planos com maior exposição para a sua empresa, por exemplo: \n" +
                    "por R$ 26,00 mensais sua empresa será vista na cidade de " + cidade + " inteira! \n \n" +
                    "Gostaria de conhecer nossos planos? \n\n";

                texto = window.encodeURIComponent(texto);
                window.open("https://api.whatsapp.com/send?phone=" + celular + "&text=" + texto, "_blank");


                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("AtualizaStatus", "Prestadores")',
                    data: {
                        "idPrestador": idPrestador,
                        "Status": 'Oportunidade'
                    },
                    success:

                    function (resultado) {
                        alert(resultado);
                    },
                });
                location.reload();

    };



    function enviarOportunidade(celular, idPrestador) {

                var celular = "55" + celular;

                var texto = "The Little Orange Club \n" +
                    "Planos Mensais  \n" +
                    "- - - - - - - - - - - - - - - - - - - - - -\n" +
                    "Cidade .... R$26,00 \n" +
                    "Estado .... R$35,00 \n" +
                    "Região .... R$53,00 \n" +
                    "País ...... R$143,00 \n" +
                    "Continental R$260,00 \n" +
                    "Global .... R$350,00 \n \n" +
                    "Planos Anuais 10% de desconto parcelado pelo PagSeguro. \n \n" +
                    "Responda aqui no whatsapp para escolher o melhor plano para sua empresa. \n\n";

                texto = window.encodeURIComponent(texto);
                window.open("https://api.whatsapp.com/send?phone=" + celular + "&text=" + texto, "_blank");


                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("AtualizaStatus", "Prestadores")',
                    data: {
                        "idPrestador": idPrestador,
                        "Status": 'Negociando'
                    },
                    success:

                    function (resultado) {
                        alert(resultado);
                    },
                });
                location.reload();

    };



    </script>
}

TheLittleOrangeChannel/TheLittleOrangeChannel/Views/PrestadoresBase/Edit.cshtml
@model TheLittleOrangeChannel.Models.tblPrestadorBase

@{
    ViewBag.Title = "Edit";

    var link_x = ViewBag.link;
    var texto_x = ViewBag.texto;
    var idStatusAtual = ViewBag.StatusAtual;
    var idStatusCadastrado = ViewBag.StatusCadastrado;
    var idStatusIndicado = ViewBag.StatusIndicado;
}

<h2>Prestadores</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Cadastro Básico</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idPrestador)
    @Html.HiddenFor(model => model.idCanal)
    @Html.HiddenFor(model => model.idStatus)
    @Html.HiddenFor(model => model.idPlano)
    @Html.HiddenFor(model => model.idFormaPagto)
    @Html.HiddenFor(model => model.dtCriacao)

    <input type="hidden" id="idStatusIndicado" Value="@ViewBag.StatusIndicado" />

    <div class="form-group">
        @Html.LabelFor(model => model.idCondominio, "Condominio", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idCondominio", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idCondominio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Empresa, "Empresa *", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Empresa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.idEspecialidade, "Especialidade *", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idEspecialidade", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idEspecialidade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Celular, "Celular *", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CPF_CNPJ, "CPF ou CNPJ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CPF_CNPJ, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CPF_CNPJ, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.idAbrangencia, "Abrangencia *", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idAbrangencia", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idAbrangencia, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.diasPromocao, "dias Promocao ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.diasPromocao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.diasPromocao, "", new { @class = "text-danger" })
        </div>
    </div>


    @*<div class="form-group">
            @Html.Label("Link whatsapp:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => link_x, new { htmlAttributes = new { @class = "form-control" } })



                <button onclick="enviarWhatsApp('@ViewBag.ShortCelular', '@ViewBag.Empresa', '@ViewBag.Condominio', '@ViewBag.Especialidade','@ViewBag.Email')" class="btn btn-success">Abrir Whatsapp</button>
            </div>

        </div>

        <div class="form-group">
            @Html.Label("Texto do convite:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => texto_x, 20, 100, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <button onclick="copiarTexto()" class="btn btn-info">Copiar para memória</button>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a href=" @Url.Action("Index")" class="btn btn-warning">Sair</a>

            @if (idStatusAtual == idStatusCadastrado)
            {
                <button onclick="enviarWhatsApp('@ViewBag.ShortCelular', '@ViewBag.Empresa', '@ViewBag.Condominio', '@ViewBag.Especialidade','@ViewBag.Email', '@ViewBag.id')" class="btn btn-success">Whatsapp</button>
            }


            @if (idStatusAtual == idStatusIndicado)
            {
                <button onclick="enviarWhatsAppIndicado('@ViewBag.ShortCelular', '@ViewBag.Empresa', '@ViewBag.Condominio', '@ViewBag.Especialidade','@ViewBag.Email', '@ViewBag.id')" class="btn btn-success">Whatsapp 2</button>
            }

            <input id="btnSalvar" type="submit" value="Salvar" class="btn btn-default" id="btnSalvar" />
        </div>
    </div>
</div>
}


 @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")


<script type="text/javascript">

        $(document).ready(function () {

            @*var escolha = "@ViewBag.Abrangencia";
            if (escolha != "") {
                Escolha("Abrangencia", escolha);
            }*@

        });

        function enviarWhatsApp(celular, empresa, condominio, especialidade, email, idPrestador) {


            var msg = "Olá " + empresa + ',  \r\n\r\n '
                + "você foi indicado como prestador de serviços no grupo de Whatsapp do \r\ncondominio " + condominio + ". \r\n\r\n"
                + "A The Little Orange criou um aplicativo onde os moradores podem indicar prestadores de serviços, para que os "
                + "outros moradores do mesmo condomínio possam usar de referência!\r\n"
                + "Como você foi indicado no grupo deste condomínio, gostaríamos de saber se você quer ser cadastrado gratuitamente em nosso aplicativo,"
                + "desta forma você poderá ser encontrado por todos os moradores deste condomínio sem custo algum.\r\n\r\n"
                + "Preencha os dados que faltam, ou altere a informação que está apresentada e faremos seu cadastro.\r\n\r\n"
                + "Em breve você receberá um e-mail e poderá acessar o nosso aplicativo.\r\n\r\n"
                + "- - - - - - - - - - - - - - - - -\r\n"
                + "P R E S T A D O R\r\n"
                + "- - - - - - - - - - - - - - - - -\r\n"
                + "Condomínio: " + condominio + "\r\n"
                + "Empresa: " + empresa + "\r\n"
                + "Especialidade: " + especialidade + "\r\n"
                + "Celular: " + celular + "\r\n"
                + "E-mail: " + email + "\r\n"
                + "CPF/CNPJ:   \r\n\r\n "
                + "https://thelittleorange.app";

            msg = window.encodeURIComponent(msg);
            window.open("https://api.whatsapp.com/send?phone=55" + celular + "&text=" + msg, "_blank");

            document.getElementById('idStatus').value = document.getElementById('idStatusIndicado').value;

            document.getElementById('btnSalvar').click();

            @*location.reload();

            $.ajax(
            {
                type: "POST",
                url: '@Url.Action("Indicado", "PrestadoresBase")',
                data: {
                    "id": idPrestador
                },
                success:

                function (resultado) {
                    alert('Prestador indicado com sucesso!!');
                },
            });*@



        }


    function enviarWhatsApp2(celular, empresa, condominio, especialidade, email, idPrestador) {

        var diasPromocao = document.getElementById('diasPromocao').value;

        var msg = "Sua empresa foi cadastrada com sucesso!! " + empresa + ',  \r\n\r\n '
            + "Em breve vai receber um e - mail com as informações de acesso a plataforma The Little Orange. \r\n\r\n"
            + "Você recebeu " + diasPromocao + " dias gratuitos para ser exibido em todo estado."
            + "Para aumentar suas visualizações entre no app e complete os dados de sua empresa!\r\n"
            + "Agora se você quiser ter destaque, pede para seus clientes te avaliarem usando o app."
            + "Imprima este flyer e deixe bem fácil para o seu cliente ver,\r\n\r\n"
            + "ele tem um QR Code que leva seu cliente direto para o app,\r\n\r\n"
            + "ali ele se cadastra e poderá dar uma nota para sua empresa!. \r\n\r\n"
            + "- - - - - - - - - - - - - - - - -\r\n"
            + "P R E S T A D O R\r\n"
            + "- - - - - - - - - - - - - - - - -\r\n"
            + "Condomínio: " + condominio + "\r\n"
            + "Empresa: " + empresa + "\r\n"
            + "Especialidade: " + especialidade + "\r\n"
            + "Celular: " + celular + "\r\n"
            + "E-mail: " + email + "\r\n"
            + "CPF/CNPJ:   \r\n\r\n "
            + "https://thelittleorange.app";

        msg = window.encodeURIComponent(msg);
        window.open("https://api.whatsapp.com/send?phone=55" + celular + "&text=" + msg, "_blank");


        document.getElementById('btnSalvar').click();


        }


</script>
 }